![arithmeticfucntions](images/arithmeticFunctions2.png)

# Shuffle

In [7]:
import numpy as np

var = np.array([1, 2, 3, 4, 5])

np.random.shuffle(var) # shuffle the array

print(var) # print the shuffled array

[3 2 4 1 5]


In [22]:
import numpy as np

var = np.array([2,2,1,5,6,7,8,9,10,6,5,4,3,2,1])

x = np.unique(var) # get the unique values
y = np.unique(var, return_index=True) # get the unique values and their indices
z = np.unique(var, return_counts=True) # get the unique values and their counts

print(x) # print the unique values
print(type(x)) # print the data type of the unique values
print()
print(y) # print the unique values and their indices
print(type(y)) # print the data type of the indices
print()
print(z) # print the unique values and their counts
print(type(z)) # print the data type of the counts

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 2,  0, 12, 11,  3,  4,  5,  6,  7,  8], dtype=int64))
<class 'tuple'>

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([2, 3, 1, 1, 2, 2, 1, 1, 1, 1], dtype=int64))
<class 'tuple'>


In [24]:
import numpy as np

var = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

y = np.resize(var, (2, 5)) # resize the array to 2x5
z = np.resize(var, (5, 2)) # resize the array to 5x2

print(y) # print the resized array
print()
print(z) # print the resized array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


![flatten](images/flatten.png)

In [30]:
import numpy as np

var = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = np.resize(var, (2, 5)) # resize the array to 2x5

z = y.flatten(order="F") # flatten the array

print(y) # print the resized array
print(z) # print the flattened array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  6  2  7  3  8  4  9  5 10]
