![Contents](images/arithmeticOperations.png)

In [3]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [5]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1 + var2
print(varadd)

[2 4 6 8]


In [7]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var - 3
print(varadd)

[-2 -1  0  1]


In [9]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1 - var2
print(varadd)

[0 0 0 0]


In [11]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var * 3
print(varadd)

[ 3  6  9 12]


In [13]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1 * var2
print(varadd)

[ 1  4  9 16]


In [3]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var% 3
print(varadd)

[1 2 0 1]


In [5]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = np.add(var1, var2)
print(varadd)

[2 4 6 8]


## 2D Array

In [10]:
import numpy as np
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
varadd = np.add(var1, var2)

print(var1)
print()
print(var2)
print()
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [12]:
import numpy as np
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
varadd = var1*var2

print(var1)
print()
print(var2)
print()
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]
