# Example of brodcast

In [4]:
import numpy as np

var1  = np.array([1,2,3,4])
var2 = np.array([1,2,3])

print(var1+var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

![Contents](images/brodcastingResolveCondition.png)

In [13]:
import numpy as np

var1  = np.array([1,2,3])
var2 = np.array([[1],[2],[3]])

print(var1)
print(var1.shape)
print()

print(var2)
print(var2.shape)
print()

x = var1+var2
print(x)
print(x.shape)

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
(3, 3)
