![Basic difference between copy and view](images/copyvsview.png)

In [3]:
import numpy as np 

var = np.array([1,2,3,4])

co = var.copy()

print(var)
print(co)
print()

var[0] = 5
print(var)
print(co) # copy() method creates a new array and does not affect the original array


[1 2 3 4]
[1 2 3 4]

[5 2 3 4]
[1 2 3 4]


In [4]:
import numpy as np 

var = np.array([1,2,3,4])

co = var.view()

print(var)
print(co)
print()

var[0] = 5
print(var)
print(co) # view() method creates a view of the original array, so the changes made in the original array will be reflected in the view array as well.


[1 2 3 4]
[1 2 3 4]

[5 2 3 4]
[5 2 3 4]
