# Initialized numpy array

In [11]:
import numpy as np
n = np.zeros([4,4])
print(n)
print("Dimention :", n.ndim)
print(type(n))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Dimention : 2
<class 'numpy.ndarray'>
