# Insert

In [3]:
import numpy as np

var  = np.array([1, 2, 3, 4, 5])

v = np.insert(var, 1, 10)
x = np.insert(var, (1,4), 10)

print(var)
print(v)
print(x)

[1 2 3 4 5]
[ 1 10  2  3  4  5]
[ 1 10  2  3  4 10  5]


In [17]:
import numpy as np

var  = np.array([[1, 2], [3, 4], [5, 6]])

x = np.insert(var, 1, 10, axis=0)   # Insert 10 at row 1
y = np.insert(var, 1, 10, axis=1)   # Insert 10 at column 1

z = np.insert(var, 1, [10, 20], axis=0)   # Insert 10 at row 1
k = np.insert(var, 1, [10, 20, 30], axis=1) 

print(var)
print()
print(x)
print()
print(y)
print()
print("np.insert(var, 1, [10, 20], axis=0) ")
print(z)
print()
print("np.insert(var, 1, [10, 20, 30], axis=1) ")
print(k)


[[1 2]
 [3 4]
 [5 6]]

[[ 1  2]
 [10 10]
 [ 3  4]
 [ 5  6]]

[[ 1 10  2]
 [ 3 10  4]
 [ 5 10  6]]

np.insert(var, 1, [10, 20], axis=0) 
[[ 1  2]
 [10 20]
 [ 3  4]
 [ 5  6]]

np.insert(var, 1, [10, 20, 30], axis=1) 
[[ 1 10  2]
 [ 3 20  4]
 [ 5 30  6]]


# Delete

In [19]:
import numpy as np

var = np.array([[1, 2], [3, 4], [5, 6]])

x = np.delete(var, 1, axis=0)   # Delete row 1
y = np.delete(var, 1, axis=1)   # Delete column 1

print(var)
print()
print(x)
print()
print(y)

[[1 2]
 [3 4]
 [5 6]]

[[1 2]
 [5 6]]

[[1]
 [3]
 [5]]
