# Iterating

## Using for loop

In [2]:
import numpy as np

var = np.array([1,3,5,6,7,4,8,9])

for i in var :
    print(i)

1
3
5
6
7
4
8
9


In [9]:
import numpy as np

var  = np.array([[1,3,4,5,6],[1,5,7,8,9]])

print(var)
print()
print(var.T)
print()
for i in var :
    print(i)  # print each row
print()
for i in var.T :
    print(i)  # print each column

print()
for j in var :
    for i in j :
        print(i)
print()
    

[[1 3 4 5 6]
 [1 5 7 8 9]]

[[1 1]
 [3 5]
 [4 7]
 [5 8]
 [6 9]]

[1 3 4 5 6]
[1 5 7 8 9]

[1 1]
[3 5]
[4 7]
[5 8]
[6 9]

1
3
4
5
6
1
5
7
8
9



## Without Loop

In [13]:
import numpy as np

var  = np.array([[1,3,4,5,6],[1,5,7,8,9]])

print(var)
print()

for i in np.nditer(var) :
    print(i)
print()

for d, i in np.ndenumerate(var) :
    print(d,i)

[[1 3 4 5 6]
 [1 5 7 8 9]]

1
3
4
5
6
1
5
7
8
9

(0, 0) 1
(0, 1) 3
(0, 2) 4
(0, 3) 5
(0, 4) 6
(1, 0) 1
(1, 1) 5
(1, 2) 7
(1, 3) 8
(1, 4) 9
