# Join

![Join](images/Join.png)

In [5]:
import numpy as np 

var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])

ar = np.concatenate((var1,var2)) #concatenates the two arrays

print(ar)

[1 2 3 4 5 6 7 8]


In [7]:
import numpy as np 

var1 = np.array([[1,2],[3,4]])
var2 = np.array([[5,6],[7,8]])

ar = np.concatenate((var1,var2),axis=1) #axis=1 means column wise concatenation

ar2 = np.concatenate((var1,var2),axis=0) #axis=0 means row wise concatenation
print(var1)
print()

print(var2)
print()

print(ar)
print()

print(ar2)
print()

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]



In [14]:
import numpy as np 

var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])

ar = np.stack((var1,var2), axis=0) ##stacks the two arrays
ar5 = np.stack((var1,var2), axis=1) ##stacks the two arrays

ar2 = np.hstack((var1,var2)) #stacks the two arrays horizontally

ar3 = np.vstack((var1,var2)) #stacks the two arrays vertically

ar4 = np.dstack((var1,var2)) #stacks the two arrays depth wise

print(ar)
print()

print(ar5)
print()

print(ar2)
print()

print(ar3)
print()

print(ar4) 
print()

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]

