# Matrix

In [5]:
import numpy as np

var =  np.matrix([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
var2 = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(var)

print()
print(var+var2)

print(type(var))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
<class 'numpy.matrix'>


In [9]:
import numpy as np

var =  np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
var2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(var)


print()
print(var+var2)


print(type(var))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
<class 'numpy.ndarray'>


In [11]:
import numpy as np

var =  np.matrix([[1, 2, 3], [5, 6, 7], [9, 10, 11]])
var2 = np.matrix([[1, 2, 3], [5, 6, 7], [9, 10, 11]])

print(var)

print()
print(var*var2) # matrix multiplication

print()
print(var.dot(var2)) # matrix multiplication


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

[[ 38  44  50]
 [ 98 116 134]
 [158 188 218]]

[[ 38  44  50]
 [ 98 116 134]
 [158 188 218]]


In [10]:
import numpy as np

var =  np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])
var2 = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])

print(var)

print()
print(var*var2) #element wise multiplication


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

[[  1   4   9]
 [ 25  36  49]
 [ 81 100 121]]


![matrixFunctions](images/matrixFunctions.png)