# Basics of  numpy
___

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Note: you may need to restart the kernel to use updated packages.


## First example of creating numpy array
---

In [6]:
import numpy as np
n =  np.array((1,2,3))
print(n)
print(type(n))

[1 2 3]
<class 'numpy.ndarray'>


In [13]:
n = np.array([1,3,3])
print(n)
print(type(n))

[1 3 3]
<class 'numpy.ndarray'>


## Creating multiple dimention array in numpy
---

In [23]:
n = np.array(25)
print(n)
print("Dimentions:", n.ndim)

25
Dimentions: 0


In [27]:
n = np.array([1,1,2])
print(n)
print("Dimentions:", n.ndim)

[1 1 2]
Dimentions: 1


In [31]:
n = np.array([[1,1,2],[1,4,5]])
print(n)
print("Dimentions:", n.ndim)

[[1 1 2]
 [1 4 5]]
Dimentions: 2
