# Search

In [2]:
import numpy as np

var = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

x = np.where(var == 2) # returns the index of the element that is equal to 2
y = np.where(var % 2 == 0) # returns the index of the elements that are even

print(x) # prints (array([1]),) because the element is at index 1
print(y) # prints (array([1, 3, 5, 7, 9]),) because the even elements are at indexes 1, 3, 5, 7, 9

(array([1], dtype=int64),)
(array([1, 3, 5, 7, 9], dtype=int64),)


## Search in sorted array

![searchsorted](images/searchsorted.png)

In [4]:
import numpy as np

var = np.array([1, 2, 3, 4, 6, 7, 8, 9, 10])

x = np.searchsorted(var, 5) # returns the index where 5 should be inserted to maintain the order of the array

y = np.searchsorted(var, [5,6,7], side='right') # returns the index where 5, 6, 7 should be inserted to maintain the order of the array

print(x) # prints 4 because 5 should be inserted at index 4 to maintain the order of the array
print(y) # prints [4 5 6] because 5, 6, 7 should be inserted at indexes 4, 5, 6 to maintain the order of the array

4
[4 5 6]


# Sort

In [5]:
import numpy as np

var  = np.array([2,6,1,9,10,3,27,8,5])

x = np.sort(var) # returns the sorted array

print(x) # prints [ 1  2  3  5  6  8  9 10 27]

[ 1  2  3  5  6  8  9 10 27]


In [7]:
import numpy as np

var =  np.array(["a","k","b","z","c","d","e","f","g","h"])

x = np.sort(var) # returns the sorted array
y = np.argsort(var) # returns the indexes of the elements after sorting
print(x) # prints ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'k' 'z']
print(y) # prints [0 2 4 5 6 7 8 9 1 3]

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'k' 'z']
[0 2 4 5 6 7 8 9 1 3]


In [15]:
import numpy as np

var = np.array([[1,5],[3,2],[6,4]])

x = np.sort(var, axis=0) # sorts the array along the first axis
y = np.sort(var, axis=1) # sorts the array along the second axis

print(x) # prints [[1 2]
            #         [3 4]
            #         [6 5]]
      
print() # prints an empty line      
print(y) # prints [[1 5]

[[1 2]
 [3 4]
 [6 5]]

[[1 5]
 [2 3]
 [4 6]]


# Filter array

![filterarray](images/filterarray.png)

In [16]:
import numpy as np

var = np.array([1, 2, 3, 4, 5])

fileter = [True, False, True, False, True]

x = var[fileter] # returns the elements that are True

print(x) # prints [1 3 5]

[1 3 5]
