# Slicing

![Slicing](images/slicing.png)

In [5]:
import numpy as np

var  = np.array([9,3,4,5,7,8,2,4,0])

print(var)

print("3 to 7", var[1:5])
print("3 to end", var[1:])
print("start to 7", var[:5])
print("Step 2", var[::2])

[9 3 4 5 7 8 2 4 0]
3 to 7 [3 4 5 7]
3 to end [3 4 5 7 8 2 4 0]
start to 7 [9 3 4 5 7]
Step 2 [9 4 7 2 0]


In [10]:
import numpy as np
var  = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print()
print("2nd row", var[1])
print()
print("5 to 6", var[1,1:3])
print()
print("5 to 9", var[1:,1:])
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

2nd row [4 5 6]

5 to 6 [5 6]

5 to 9 [[5 6]
 [8 9]]

