# Split array

In [3]:
import numpy as np 

var  = np.array([1,2,3,4,5,6])

ar = np.split(var, 3) # split into 3 arrays

print(ar) 
print(ar[0]) # print first array
print(ar[1]) # print second array

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]


In [6]:
import numpy as np

var = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

ar1  = np.split(var, 3) # split into 3 arrays
ar2  = np.split(var, 2, axis=1) # split into 2 arrays along the second axis

print(var)
print()

print(ar1)
print()

print(ar2)
print()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]

